
export const datasLanguage = {
    'UA': {
        header: {
            heartBtn: 'Обрані',
            cartBtn: 'Кошик',
            loginBtn: 'Вхід',
            placeholderSearch: 'Пошук',
        },
        footer: {
            catalogTitle: 'Каталог',
            contactTitle: 'Контакт',
            aboutMenuTitle: 'Про компанію',
            callMeBack: 'Передзвоніть мені',
            subscribeNews : 'Підпишіться на новини та акції',
            subscribeBtn : 'Підписка',
            licenseText1 : '© 2019 - 2022 «Goldi». Всі права захищенно',
            licenseText2 : 'Розроблений та підтримується компанією',
        },
        homePage: {
            homeName: 'Головна сторінка',
            homeInfoTitle: 'Інтернет-магазин',
            titleSwiperDiscounts: 'Знижки',
            titleSwiperNew: 'Новинки',
        },
        categoriesPage: {
            categoriesSortTitle: 'Сортування:',
            categoriesSortOption1: 'По зростанню ціни:',
            categoriesSortOption2: 'По спаданню ціни:',
            categoriesSortOption3: 'Знижки:',
            categoriesSortOption4: 'Новинки:',
            categoriesError: 'В цій категорії не має товарів',
        },
        productPage: {
            productSizeTitle: 'Доступні розміра: ',
            productColorsTitle: 'Доступні кольори: ',
            productDescriptionTitle: 'Опис',
            productBtnWishListAdd: 'Добавити в обрані',
            productBtnWishListNotAdd: 'Видалити з обраних',
            productBtnCartAdd: 'Добавити в кошик',
            productBtnCartNotAdd: 'Видалити з кошика',
            productGuaranteeTitle: 'Гарантія',
            productDeliveryTitle: 'Способи доставки:',
            productPaymentTitle: 'Способи оплати:',
            productSwiperTitle: 'Подібні продукти',
            productLastTitle: 'Переглянуті продукти',
        },
        wishlistPage: {
            wishlistName: 'Обрані',
            wishlistError: 'У вас немає обраних товарів!!!',
        },
        cartPage: {
            cartName: 'Кошик',
            cartPriceTitle: 'Ціна:',
            cartTotalPriceTitle: 'Загальна ціна:',
            cartQuantityTitle: 'Введіть кількість',
            cartTotalTitle: 'Загальна сума:',
            cartBtnBuy: 'Оформити замовлення',
            cartError: 'Ваш кошик пустий!!!',
            cartFormTitle: 'Контактна інформація',
            cartFormWarning: 'Ці поля обов\'язкові для заповнення',
            cartFormName: 'Прізвище та ім\'я',
            cartFormPhone: 'Телефон',
            cartFormMail: 'Ел. пошта',
            cartFormComment: 'Коментар:',
            cartFormCheckbox: 'Даю згоду на обробку даних',
            cartFormSubmitError: 'Обовязкові поля не заповнені!!!',
        },
        notFoundPage: {
            notFoundTitle: 'Сторінка не знайдена',
            notFoundGetBackTitle: 'Повернутись на головну сторінку:',
        },
    },
    'ENG': {
        header: {
            heartBtn: 'Chosen',
            cartBtn: 'Basket',
            loginBtn: 'Exit',
            placeholderSearch: 'Search',
        },
        footer: {
            catalogTitle: 'Catalogue',
            contactTitle: 'Contact',
            aboutMenuTitle: 'About the company',
            callMeBack: 'Call me back',
            subscribeNews : 'Subscribe to news and promotions',
            subscribeBtn : 'Subscription',
            licenseText1 : '© 2019 - 2022 «Goldi». All rights reserved',
            licenseText2 : 'Developed and maintained by the company',
        },
        homePage: {
            homeName: 'Main page',
            homeInfoTitle: 'Internet-shope',
            titleSwiperDiscounts: 'Discounts',
            titleSwiperNew: 'Novelty',
        },
        categoriesPage: {
            categoriesSortTitle: 'Sorting:',
            categoriesSortOption1: 'As the price increases',
            categoriesSortOption2: 'As the price drops',
            categoriesSortOption3: 'Discounts',
            categoriesSortOption4: 'Novelty',
            categoriesError: 'There are no products in this category',
        },
        productPage: {
            productSizeTitle: 'Available sizes: ',
            productColorsTitle: 'Available colors: ',
            productDescriptionTitle: 'Description',
            productBtnWishListAdd: 'Add to favorites',
            productBtnWishListNotAdd: 'Remove from favorites',
            productBtnCartAdd: 'Add to cart',
            productBtnCartNotAdd: 'Remove from cart',
            productGuaranteeTitle: 'Guarantee',
            productDeliveryTitle: 'Delivery methods:',
            productPaymentTitle: 'Payment methods:',
            productSwiperTitle: 'Similar products',
            productLastTitle: 'Reviewed products',
        },
        wishlistPage: {
            wishlistName: 'Chosen',
            wishlistError: 'You have no selected products!!!',
        },
        cartPage: {
            cartName: 'Basket',
            cartPriceTitle: 'Price:',
            cartTotalPriceTitle: 'Total price:',
            cartQuantityTitle: 'Enter the quantity',
            cartTotalTitle: 'Total:',
            cartBtnBuy: 'To order',
            cartError: 'Your basket is empty!!!',
            cartFormTitle: 'Contact information',
            cartFormWarning: 'These fields are mandatory',
            cartFormName: 'Name and surname',
            cartFormPhone: 'Phone',
            cartFormMail: 'E. mail',
            cartFormComment: 'Comment:',
            cartFormCheckbox: 'I consent to data processing',
            cartFormSubmitError: 'Mandatory fields are not filled!!!',
        },
        notFoundPage: {
            notFoundTitle: 'Page not found',
            notFoundGetBackTitle: 'Return to the main page:',
        },
    },
  
}

