
export const languageUser = {
    'UA': {
        signUpView: {
            signUpSliderTitle1: 'Створення інтернет магазину', 
            signUpSliderTitle2: 'Розвиток вашого бізнесу', 
            signUpSliderTitle3: 'Допомого в досягненні мрії', 
            signUpSliderSubTitle1: 'Створення інтернет магазину Створення інтернет магазину', 
            signUpSliderSubTitle2: 'Створення інтернет магазину Створення інтернет магазину', 
            signUpSliderSubTitle3: 'Створення інтернет магазину Створення інтернет магазину', 
            signUpCompanyName: 'Назва фірми', 
            signUpCreateTitle: 'Створити акаунт',
            signUpGoToTitle: 'Перейти на сторінку',
            signUpNameTitle: 'Ім\'я',
            signUpNamePlaceholder: 'Введіть ім\'я...',
            signUpSurnameTitle: 'Фамілія',
            signUpSurnamePlaceholder: 'Введіть прізвище...',
            signUpEmailTitle: 'Емейл',
            signUpEmailPlaceholder: 'Введіть емейл...',
            signUpPasswordTitle: 'Пароль',
            signUpPasswordError: 'Не правельно введений повторний пароль',
            signUpPasswordPlaceholder: 'Введіть пароль...',
            signUpPasswordRepeatTitle: 'Повторіть пароль',
            signUpPasswordRepeatPlaceholder: 'Введіть пароль...',
            signUpCreateBtn: 'Створити',
            signUpReturnToTitle: 'Повернутись на',
            signUpMainPage: 'Головну',
        },
        SignInView: {
            signInSliderTitle1: 'Створення інтернет магазину', 
            signInSliderTitle2: 'Розвиток вашого бізнесу', 
            signInSliderTitle3: 'Допомого в досягненні мрії', 
            signInSliderSubTitle1: 'Створення інтернет магазину Створення інтернет магазину', 
            signInSliderSubTitle2: 'Створення інтернет магазину Створення інтернет магазину', 
            signInSliderSubTitle3: 'Створення інтернет магазину Створення інтернет магазину', 
            signInCompanyName: 'Назва фірми', 
            signInTitle: 'Увійти',
            signInSubTitle: 'Не маєте облікового запису?', 
            signInEmailTitle: 'Емейл',
            signInEmailPlaceholder: 'Введіть емейл...',
            signInPasswordTitle: 'Пароль',
            signInPasswordPlaceholder: 'Введіть пароль...',
            signInLeavePassword: 'Забули пароль?',
            signInLogiBtn: 'Авторизуватися',
            signInReturnToTitle: 'Повернутись на',
            signInMainPage: 'Головну',
        },
        layoutUser: {
            layoutCompanyName: 'Назва сайту',
            layoutLinkAnalytics: 'Аналітика',
            layoutLinkShop: 'Магазин',
            layoutLinkCategories: 'Категорії',
            layoutLinkProducts: 'Товар',
            layoutLinkOrders: 'Зомовлення',
            layoutLinkMessage: 'Повідомлення',
            layoutLinkExit: 'Вихід',
        },
        userShopView: {
            userShopTitle: 'Магазин',
            userShopInfoName: 'Назва магазину:',
            userShopInfoTel: 'Контакний номер телефону:',
            userShopInfoTel2: 'Додатковий контакний номер телефону:',
            userShopInfoAddress: 'Адреса:',
            userShopInfoCurrency: 'Валюта:',
            userShopInfoLanguage: 'Мова сайту:',
            userShopInfoDelivery: 'Способи доставки:',
            userShopInfoPayment: 'Способи оплати:',
            userShopInfoDescription: 'Опис магазину:',
            userShopInfoLogo: 'Логотип:',
            userShopEditBtn: 'Редагувати',
            userShopBlockMainTitle: 'Добавити блок інформації',
            userShopBlockTitle: 'Введіть заголовок',
            userShopBlockText: 'Введіть текст',
            userShopBlockHeaderColor: 'Колір заголовка',
            userShopBlockTextColor: 'Колір тексту',
            userShopBlockBackgroundColor: 'Колір фону',
            userShopBlockTextAlign: 'Вирівнювання тексту',
            userShopBlockTitleShadow: 'Тінь заголовка',
            userShopBlockTextShadow: 'Тінь тексту',
            userShopBlockHeaderSize: 'Розмір заголовку',
            userShopBlockHeaderThickness: 'Товщина заголовку',
            userShopBlockTextSize: 'Розмір тексту',
            userShopBlockTextThickness: 'Товщина тексту',
            userShopBlockShadowX: 'Тінь по Х',
            userShopBlockShadowY: 'Тінь по Y',
            userShopBlockShadowZ: 'Тінь по Z',
            userShopBlockShadowTransparency: 'Прозорість тіні',
            userShopBlockRemoveBtn: 'Видалити',
            userShopBlockCreateBtn: 'Створити',
            userShopBlockInstruction: 'Заповніть блок інформацією і нажміть створити. Блок появиться на головній сторінці магазину.',
            userShopBlockViewTitle: 'Вигляд блоку',
            userShopBlockCheckboxStart: 'Початок',
            userShopBlockCheckboxCenter: 'Центер',
            userShopBlockCheckboxEnd: 'Кінець',
        },
        userCategoriesView: {
            userCategoriesModalDelCatTitle: 'Ви впевнені?',
            userCategoriesModalDelCatText: 'Всі підкатегорії даної категорії будуть видалені',
            userCategoriesModalDelCatLeftBtn: 'Ні',
            userCategoriesModalDelCatRightBtn: 'Так',
            userCategoriesModalDelSubCatTitle: 'Ви впевнені?',
            userCategoriesModalDelSubCatText: 'Видалити дану категорію',
            userCategoriesModalDelSubCatLeftBtn: 'Ні',
            userCategoriesModalDelSubCatRightBtn: 'Так',
            userCategoriesModalEditSubCatTitle: 'Редагувати категорію?',
            userCategoriesModalEditSubCatText: 'Введіть нову назву',
            userCategoriesModalEditCatLeftBtn: 'Відмінити',
            userCategoriesModalEditCatRightBtn: 'Підтвердити',
            userCategoriesTitle: 'Мої категорії',
            userCategoriesErrorCreateLimit: 'Ви дасягнули ліміту категорій',
            userCategoriesErrorCreate: 'Спершу потрібно створити магазин',
            userCategoriesCreateLabelName: 'Назва категорії',
            userCategoriesCreateNamePlaceholder: 'Введіть назву...',
            userCategoriesCreateLabelImg: 'Картинка',
            userCategoriesCreateCatBtn: 'Створоти категорію',
            userCategoriesCreateCatInfo: 'Для створення категорії Впишіть її назву і нажміть на кнопку створити. Кількість категорій обмежена до "5". Для коректного відображення картинок, формат картинки повинен бути 16:9. Щоб створити категорію, спершу потрібно створити магазин. Після створення категорії зможете створювати підкатегорії.',
            userCategoriesCardTitle: 'Назва категорії:',
            userCategoriesCreateSub: 'Створити підкатегорію',
            userCategoriesSubTitle: 'Підкатегорії:',
        },
        cardInput: {
            cardInputPlaceholder: 'Введіть назву...'
        },
    },
    'ENG': {
        signUpView: {
            signUpSliderTitle1: 'Creation of an online store', 
            signUpSliderTitle2: 'Development of your business', 
            signUpSliderTitle3: 'Help in achieving the dream', 
            signUpSliderSubTitle1: 'Creating an online store Creating an online store', 
            signUpSliderSubTitle2: 'Creating an online store Creating an online store', 
            signUpSliderSubTitle3: 'Creating an online store Creating an online store', 
            signUpCompanyName: 'Company name',
            signUpCreateTitle: 'Create account',
            signUpGoToTitle: 'Go to page',
            signUpNameTitle: 'Name',
            signUpNamePlaceholder: 'Enter a name...',
            signUpSurnameTitle: 'Surname',
            signUpSurnamePlaceholder: 'Enter last name...',
            signUpEmailTitle: 'Mail',
            signUpEmailPlaceholder: 'Enter your email...',
            signUpPasswordTitle: 'Password',
            signUpPasswordError: 'The repeated password is not entered correctly',
            signUpPasswordPlaceholder: 'Enter your password...',
            signUpPasswordRepeatTitle: 'Repeat the password',
            signUpPasswordRepeatPlaceholder: 'Enter your password...',
            signUpCreateBtn: 'Create',
            signUpReturnToTitle: 'Return to',
            signUpMainPage: 'Main page',
        },
        SignInView: {
            signInSliderTitle1: 'Creation of an online store', 
            signInSliderTitle2: 'Development of your business', 
            signInSliderTitle3: 'Help in achieving the dream', 
            signInSliderSubTitle1: 'Creating an online store Creating an online store', 
            signInSliderSubTitle2: 'Creating an online store Creating an online store', 
            signInSliderSubTitle3: 'Creating an online store Creating an online store', 
            signUpCompanyName: 'Company name',
            signInTitle: 'Sign in',
            signInSubTitle: 'Don\'t have an account?',
            signInEmailTitle: 'Mail',
            signInEmailPlaceholder: 'Enter your email...',
            signInPasswordTitle: 'Password',
            signInPasswordPlaceholder: 'Enter your password...',
            signInLeavePassword: 'Forgot your password?',
            signInLogiBtn: 'Log in',
            signInReturnToTitle: 'Return to',
            signInMainPage: 'Main page',
        },
        layoutUser: {
            layoutCompanyName: 'Site Name',
            layoutLinkAnalytics: 'Analytics',
            layoutLinkShop: 'Shop',
            layoutLinkCategories: 'Categories',
            layoutLinkProducts: 'Product',
            layoutLinkOrders: 'Orders',
            layoutLinkMessage: 'Message',
            layoutLinkExit: 'Exit',
        },
        userShopView: {
            userShopTitle: 'Shop',
            userShopInfoName: 'Shop name:',
            userShopInfoTel: 'Contact phone number:',
            userShopInfoTel2: 'Additional contact phone number:',
            userShopInfoAddress: 'Address:',
            userShopInfoCurrency: 'Currency:',
            userShopInfoLanguage: 'Site language:',
            userShopInfoDelivery: 'Delivery methods:',
            userShopInfoPayment: 'Payment methods:',
            userShopInfoDescription: 'Description of the store:',
            userShopInfoLogo: 'Logo:',
            userShopEditBtn: 'Edit',
            userShopBlockMainTitle: 'Add a block of information',
            userShopBlockTitle: 'Enter a title',
            userShopBlockText: 'Enter the text',
            userShopBlockHeaderColor: 'Header color',
            userShopBlockTextColor: 'Text color',
            userShopBlockBackgroundColor: 'Background color',
            userShopBlockTextAlign: 'Text alignment',
            userShopBlockTitleShadow: 'Title shadow',
            userShopBlockTextShadow: 'Text shadow',
            userShopBlockHeaderSize: 'Header size',
            userShopBlockHeaderThickness: 'Header thickness',
            userShopBlockTextSize: 'Text size',
            userShopBlockTextThickness: 'Text thickness',
            userShopBlockShadowX: 'Shadow by X',
            userShopBlockShadowY: 'Shadow by Y',
            userShopBlockShadowZ: 'Shadow by Z',
            userShopBlockShadowTransparency: 'Shadow transparency',
            userShopBlockRemoveBtn: 'Remove',
            userShopBlockCreateBtn: 'Create',
            userShopBlockInstruction: 'Fill in the block with information and click create. The block will appear on the main page of the store.',
            userShopBlockViewTitle: 'Block view',
            userShopBlockCheckboxStart: 'Start',
            userShopBlockCheckboxCenter: 'Center',
            userShopBlockCheckboxEnd: 'End',
        },  
        userCategoriesView: {
            userCategoriesModalDelCatTitle: 'Are you sure?',
            userCategoriesModalDelCatText: 'All subcategories of this category will be deleted',
            userCategoriesModalDelCatLeftBtn: 'No',
            userCategoriesModalDelCatRightBtn: 'Yes',
            userCategoriesModalDelSubCatTitle: 'Are you sure?',
            userCategoriesModalDelSubCatText: 'Delete this category',
            userCategoriesModalDelSubCatLeftBtn: 'No',
            userCategoriesModalDelSubCatRightBtn: 'Yes',
            userCategoriesModalEditSubCatTitle: 'Edit category?',
            userCategoriesModalEditSubCatText: 'Enter a new name',
            userCategoriesModalEditCatLeftBtn: 'Cancel',
            userCategoriesModalEditCatRightBtn: 'Confirm',
            userCategoriesTitle: 'My categories',
            userCategoriesErrorCreateLimit: 'You have reached the category limit',
            userCategoriesErrorCreate: 'First you need to create a store',
            userCategoriesCreateLabelName: 'Category name',
            userCategoriesCreateNamePlaceholder: 'Enter a name...',
            userCategoriesCreateLabelImg: 'Picture',
            userCategoriesCreateCatBtn: 'Create a category',
            userCategoriesCreateCatInfo: 'To create a category, enter its name and click the create button. The number of categories is limited to "5". For the correct display of pictures, the picture format should be 16:9. To create a category, you must first create a store. After creating a category, you can create subcategories.',
            userCategoriesCardTitle: 'Category name:',
            userCategoriesCreateSub: 'Create a subcategory',
            userCategoriesSubTitle: 'Subcategories:',
        },
        cardInput: {
            cardInputPlaceholder: 'Enter a name...'
        },
    },
  
}

