
export const languageUser = {
    'UA': {
        signUpView: {
            signUpSliderTitle1: 'Створення інтернет магазину', 
            signUpSliderTitle2: 'Розвиток вашого бізнесу', 
            signUpSliderTitle3: 'Допомого в досягненні мрії', 
            signUpSliderSubTitle1: 'Створення інтернет магазину Створення інтернет магазину', 
            signUpSliderSubTitle2: 'Створення інтернет магазину Створення інтернет магазину', 
            signUpSliderSubTitle3: 'Створення інтернет магазину Створення інтернет магазину', 
            signUpCompanyName: 'Назва фірми', 
            signUpCreateTitle: 'Створити акаунт',
            signUpGoToTitle: 'Перейти на сторінку',
            signUpNameTitle: 'Ім\'я',
            signUpNamePlaceholder: 'Введіть ім\'я...',
            signUpSurnameTitle: 'Фамілія',
            signUpSurnamePlaceholder: 'Введіть прізвище...',
            signUpEmailTitle: 'Емейл',
            signUpEmailPlaceholder: 'Введіть емейл...',
            signUpPasswordTitle: 'Пароль',
            signUpPasswordError: 'Не правельно введений повторний пароль',
            signUpPasswordPlaceholder: 'Введіть пароль...',
            signUpPasswordRepeatTitle: 'Повторіть пароль',
            signUpPasswordRepeatPlaceholder: 'Введіть пароль...',
            signUpCreateBtn: 'Створити',
            signUpReturnToTitle: 'Повернутись на',
            signUpMainPage: 'Головну',
        },
        SignInView: {
            signInSliderTitle1: 'Створення інтернет магазину', 
            signInSliderTitle2: 'Розвиток вашого бізнесу', 
            signInSliderTitle3: 'Допомого в досягненні мрії', 
            signInSliderSubTitle1: 'Створення інтернет магазину Створення інтернет магазину', 
            signInSliderSubTitle2: 'Створення інтернет магазину Створення інтернет магазину', 
            signInSliderSubTitle3: 'Створення інтернет магазину Створення інтернет магазину', 
            signInCompanyName: 'Назва фірми', 
            signInTitle: 'Увійти',
            signInSubTitle: 'Не маєте облікового запису?', 
            signInEmailTitle: 'Емейл',
            signInEmailPlaceholder: 'Введіть емейл...',
            signInPasswordTitle: 'Пароль',
            signInPasswordPlaceholder: 'Введіть пароль...',
            signInLeavePassword: 'Забули пароль?',
            signInLogiBtn: 'Авторизуватися',
            signInReturnToTitle: 'Повернутись на',
            signInMainPage: 'Головну',
        },
        layoutUser: {
            layoutCompanyName: 'Назва сайту',
            layoutLinkAnalytics: 'Аналітика',
            layoutLinkShop: 'Магазин',
            layoutLinkCategories: 'Категорії',
            layoutLinkProducts: 'Товар',
            layoutLinkOrders: 'Зомовлення',
            layoutLinkMessage: 'Повідомлення',
            layoutLinkSettings: 'Налаштування',
            layoutLinkExit: 'Вихід',
        },
        userShopView: {
            userShopTitle: 'Магазин',
            userShopInfoName: 'Назва магазину:',
            userShopInfoTel: 'Контакний номер телефону:',
            userShopInfoTel2: 'Додатковий контакний номер телефону:',
            userShopInfoAddress: 'Адреса:',
            userShopInfoCurrency: 'Валюта:',
            userShopInfoLanguage: 'Мова сайту:',
            userShopInfoDelivery: 'Способи доставки:',
            userShopInfoPayment: 'Способи оплати:',
            userShopInfoDescription: 'Опис магазину:',
            userShopInfoLogo: 'Логотип:',
            userShopEditBtn: 'Редагувати',
            userShopBlockMainTitle: 'Добавити блок інформації',
            userShopBlockTitle: 'Введіть заголовок',
            userShopBlockText: 'Введіть текст',
            userShopBlockHeaderColor: 'Колір заголовка',
            userShopBlockTextColor: 'Колір тексту',
            userShopBlockBackgroundColor: 'Колір фону',
            userShopBlockTextAlign: 'Вирівнювання тексту',
            userShopBlockTitleShadow: 'Тінь заголовка',
            userShopBlockTextShadow: 'Тінь тексту',
            userShopBlockHeaderSize: 'Розмір заголовку',
            userShopBlockHeaderThickness: 'Товщина заголовку',
            userShopBlockTextSize: 'Розмір тексту',
            userShopBlockTextThickness: 'Товщина тексту',
            userShopBlockShadowX: 'Тінь по Х',
            userShopBlockShadowY: 'Тінь по Y',
            userShopBlockShadowZ: 'Тінь по Z',
            userShopBlockShadowTransparency: 'Прозорість тіні',
            userShopBlockRemoveBtn: 'Видалити',
            userShopBlockCreateBtn: 'Створити',
            userShopBlockInstruction: 'Заповніть блок інформацією і нажміть створити. Блок появиться на головній сторінці магазину.',
            userShopBlockViewTitle: 'Вигляд блоку',
            userShopBlockCheckboxStart: 'Початок',
            userShopBlockCheckboxCenter: 'Центер',
            userShopBlockCheckboxEnd: 'Кінець',
        },
        userCategoriesView: {
            userCategoriesModalDelCatTitle: 'Ви впевнені?',
            userCategoriesModalDelCatText: 'Всі підкатегорії даної категорії будуть видалені',
            userCategoriesModalDelCatLeftBtn: 'Ні',
            userCategoriesModalDelCatRightBtn: 'Так',
            userCategoriesModalDelSubCatTitle: 'Ви впевнені?',
            userCategoriesModalDelSubCatText: 'Видалити дану категорію',
            userCategoriesModalDelSubCatLeftBtn: 'Ні',
            userCategoriesModalDelSubCatRightBtn: 'Так',
            userCategoriesModalEditSubCatTitle: 'Редагувати категорію?',
            userCategoriesModalEditSubCatText: 'Введіть нову назву',
            userCategoriesModalEditCatLeftBtn: 'Відмінити',
            userCategoriesModalEditCatRightBtn: 'Підтвердити',
            userCategoriesTitle: 'Мої категорії',
            userCategoriesErrorCreateLimit: 'Ви дасягнули ліміту категорій',
            userCategoriesErrorCreate: 'Спершу потрібно створити магазин',
            userCategoriesCreateLabelName: 'Назва категорії',
            userCategoriesCreateNamePlaceholder: 'Введіть назву...',
            userCategoriesCreateLabelImg: 'Картинка',
            userCategoriesCreateCatBtn: 'Створоти категорію',
            userCategoriesCreateCatInfo: 'Для створення категорії Впишіть її назву і нажміть на кнопку створити. Кількість категорій обмежена до "5". Для коректного відображення картинок, формат картинки повинен бути 16:9. Щоб створити категорію, спершу потрібно створити магазин. Після створення категорії зможете створювати підкатегорії.',
            userCategoriesCardTitle: 'Назва категорії:',
            userCategoriesCreateSub: 'Створити підкатегорію',
            userCategoriesSubTitle: 'Підкатегорії:',
        },
        inputText: {
            inputTextPlaceholder: 'Введіть...'
        },
        inputTextarea: {
            inputTextareaPlaceholder: 'Введіть...'
        },
        creationShop: {
            creationShopTitle1: 'Створення магазину',
            creationShopTitle2: 'Оновлення магазину',
            creationShopInputNameLabel: 'Ім\'я магазину',
            creationShopInputNamePlaceholder: 'Введіть ім\'я магазину...',
            creationShopNameInfo: 'Введіть ім\'я магазину.',
            creationShopInputFacebookPlaceholder: 'Введіть facebook url...',
            creationShopFacebookInfo: 'Введіть url адресу сторінки facebook, щоб Ваші клієнти мали змогу контактувати і стежити за Вашими публікаціями.',
            creationShopInputInstagramPlaceholder: 'Введіть instagram url...',
            creationShopInstagramInfo: 'Введіть url адресу сторінки instagram, щоб Ваші клієнти мали змогу контактувати і стежити за Вашими публікаціями.',
            creationShopInputTelLabel: 'Телефон для контакту',
            creationShopInputTelPlaceholder: 'Телефон...',
            creationShopTelInfo: 'Введіть телефон за яким клієнти зможуть з Вами звязатись. В форматі ХХХ-ХХХ-ХХХХ',
            creationShopInputTel2Label: 'Додатковий телефон для контакту',
            creationShopInputTel2Placeholder: 'Телефон...',
            creationShopTel2Info: 'Введіть додатковий телефон за яким клієнти зможуть з Вами звязатись. В форматі ХХХ-ХХХ-ХХХХ',
            creationShopInputAddressLabel: 'Адреса магазину',
            creationShopInputAddressPlaceholder: 'Адрес...',
            creationShopAddressInfo: 'Введіть адресу Вашого магазину',
            creationShopInputDeliveryLabel: 'Доставка',
            creationShopInputDeliveryPlaceholder: 'Доставка...',
            creationShopDeliveryInfo: 'Введіть способи доставки товару у Вашому магазині',
            creationShopInputPaymentLabel: 'Оплата',
            creationShopInputPaymentPlaceholder: 'Оплата...',
            creationShopPaymentInfo: 'Введіть способи оплати товару у Вашому магазині',
            creationShopInputDescriptionLabel: 'Опис',
            creationShopInputDescriptionPlaceholder: 'Введіть опис...',
            creationShopDescriptionInfo: 'Введіть декілька слів про Ваш магазин.',
            creationShopInputCurrencyLabel: 'Валюта',
            creationShopCurrencyInfo: 'Введіть валюту в якій будуть зазначені ціни на товар, в форматі $ € ₴ ...',
            creationShopInputLanguageLabel: 'Мова',
            creationShopLanguageInfo: 'Виберіть мову на якій буде Ваш магазин',
            creationShopInputLogoLabel: 'Логотип',
            creationShopLogoInfo: 'Виберіть логотип Вашого магазину',
            creationShopCancelBtn: 'Відмінити',
            creationShopUpdateBtn: 'Оновити',
            creationShopCreateBtn: 'Створити',
        },
        userProduct: {
            userProductTitle: 'Мої товари',
            userProductSubTitle: 'Загальна кількість:',
            userProductModalDelTitle: 'Ви впевнені?',
            userProductModalDelText: 'Видалити даний товар',
            userProductModalDelLeftBtn: 'Ні',
            userProductModalDelRightBtn: 'Так',
            userProductCreateBtn: 'Створити товар',
            userProductSearchLabel: 'Пошук товару',
            userProductSearchPlaceholder: 'Введіть назву...',
            userProductSortLabel: 'Сортувати:',
            userProductSortOptionAll: 'Всі товари',
            userProductCardName: 'Назва товару:',
            userProductCardCategory: 'Категорія:',
            userProductCardPrice: 'Ціна товару:',
            userProductCardNewPrice: 'Ціна зі знижкою:',
            userProductCardColors: 'Доступні кольори:',
            userProductCardSizes: 'Доступні розміра:',
            userProductCardDescription: 'Опис:',
            userProductProductMissing: 'Товар відсутній',
        },
        creationProduct: {
            creationProductNameLabel: 'Назва товару',
            creationProductNameInfo: 'Введіть ім\'я товару. Товар без назви, категорії і ціни не буде відображатись в Вашому магазині.',
            creationProductCategoryTitle: 'Категорія:',
            creationProductCategoryLabel: 'Виберіть категорію товару',
            creationProductCategoryPlaceholder: 'Пошук ...',
            creationProductCategoryInfo: 'Виберіть категорію товару.',
            creationProductPriceLabel: 'Ціна',
            creationProductPriceInfo: 'Введіть ціну на товар',
            creationProductNewPriceLabel: 'Ціна на товар, якщо є знижка',
            creationProductNewPriceInfo: 'Якщо на товар є знижка введіь ціну з урахуванням знижки',
            creationProductDescriptionLabel: 'Опис товару',
            creationProductDescriptionPlaceholder: 'Опис...',
            creationProductDescriptionInfo: 'Введіть опис товару',
            creationProductColorsLabel: 'Доступні кольори',
            creationProductColorsInfo: 'Введіть назви кольорів вашого товару',
            creationProductSizesLabel: 'Доступні розміра',
            creationProductSizesInfo: 'Введіть доступні розміра вашого товару',
            creationProductPicturesLabel: 'Картинки',
            creationProductPicturesInfo: 'Загрузіть картинки товару.',
            creationProductWarningText: 'Ці поля обов\'язкові для заповнення',
            creationProductCancelBtn: 'Cancel',
            creationProductUpdateBtn: 'Update',
            creationProductCreateBtn: 'Create',
        },
        userPurchases: {
            userPurchasesTitle: 'Мої замовлення',
            userPurchasesSortTitle: 'Статус:',
            userPurchasesSortOption1: 'Всі',
            userPurchasesSortOption2: 'В процесі',
            userPurchasesSortOption3: 'Виконано',
            userPurchasesSortOption4: 'Відхилено',
            userPurchasesFilterTitle: 'Вибрати всі:',
            userPurchasesStatusTitle: 'Статус',
            userPurchasesErrorText: 'Список повідомлень пустий',
        },
        selectStatus: {
            selectStatusOption1: 'В процесі',
            selectStatusOption2: 'Виконано',
            selectStatusOption3: 'Відхилено',
        },
        readPurchasesView: {
            readPurchasesModDelTitle: 'Ви впевнені?',
            readPurchasesModDelText1: 'Відновити даний товар',
            readPurchasesModDelText2: 'Видалити даний товар',
            readPurchasesModEditTitle: 'Редагувати',
            readPurchasesModEditText: 'Введіть нове значення',
            readPurchasesModEditLeftBtn: 'Відмінити',
            readPurchasesModEditRightBtn: 'Підтвердити',
            readPurchasesOrderTitle: 'Замовлення:',
            readPurchasesStatusTitle: 'Статус:',
            readPurchasesStatusOption1: 'В процесі:',
            readPurchasesStatusOption2: 'Виконано:',
            readPurchasesStatusOption3: 'Відхилено:',
            readPurchasesInfoNameTitle: 'Замовник:',
            readPurchasesInfoTelTitle: 'Телефон:',
            readPurchasesInfoEmailTitle: 'Емейл:',
            readPurchasesInfoAddressTitle: 'Адреса:',
            readPurchasesInfoDeliveryTitle: 'Спосіб доставки:',
            readPurchasesInfoPaymentTitle: 'Спосіб оплати:',
            readPurchasesInfoCommentTitle: 'Коментар:',
            readPurchasesTextareaLabel: 'Зробити нотатки',
            readPurchasesTextareaPlaceholder: 'Нотатки...',
            readPurchasesListNotesTitle: 'Важливо!!!',
            readPurchasesProductsListTitle: 'Замовлений товар',
            readPurchasesProductsCountTitle: 'Кількість товару:',
            readPurchasesProductsTotalTitle: 'Сума замовлення:',
            readPurchasesCardNameTitle: 'Назва товару:',
            readPurchasesCardCategoryTitle: 'Категорія:',
            readPurchasesCardPriceTitle: 'Ціна товару:',
            readPurchasesCardPrice2Title: 'Ціна зі знижкою:',
            readPurchasesCardColorsTitle: 'Замовлені кольори:',
            readPurchasesCardSizeTitle: 'Замовлені розміра:',
            readPurchasesCardDescriptionTitle: 'Опис:',
            readPurchasesCardCountTitle: 'Кількість:',
            readPurchasesCardSumTitle: 'Сума:',
        },

    },
    'ENG': {
        signUpView: {
            signUpSliderTitle1: 'Creation of an online store', 
            signUpSliderTitle2: 'Development of your business', 
            signUpSliderTitle3: 'Help in achieving the dream', 
            signUpSliderSubTitle1: 'Creating an online store Creating an online store', 
            signUpSliderSubTitle2: 'Creating an online store Creating an online store', 
            signUpSliderSubTitle3: 'Creating an online store Creating an online store', 
            signUpCompanyName: 'Company name',
            signUpCreateTitle: 'Create account',
            signUpGoToTitle: 'Go to page',
            signUpNameTitle: 'Name',
            signUpNamePlaceholder: 'Enter a name...',
            signUpSurnameTitle: 'Surname',
            signUpSurnamePlaceholder: 'Enter last name...',
            signUpEmailTitle: 'Mail',
            signUpEmailPlaceholder: 'Enter your email...',
            signUpPasswordTitle: 'Password',
            signUpPasswordError: 'The repeated password is not entered correctly',
            signUpPasswordPlaceholder: 'Enter your password...',
            signUpPasswordRepeatTitle: 'Repeat the password',
            signUpPasswordRepeatPlaceholder: 'Enter your password...',
            signUpCreateBtn: 'Create',
            signUpReturnToTitle: 'Return to',
            signUpMainPage: 'Main page',
        },
        SignInView: {
            signInSliderTitle1: 'Creation of an online store', 
            signInSliderTitle2: 'Development of your business', 
            signInSliderTitle3: 'Help in achieving the dream', 
            signInSliderSubTitle1: 'Creating an online store Creating an online store', 
            signInSliderSubTitle2: 'Creating an online store Creating an online store', 
            signInSliderSubTitle3: 'Creating an online store Creating an online store', 
            signUpCompanyName: 'Company name',
            signInTitle: 'Sign in',
            signInSubTitle: 'Don\'t have an account?',
            signInEmailTitle: 'Mail',
            signInEmailPlaceholder: 'Enter your email...',
            signInPasswordTitle: 'Password',
            signInPasswordPlaceholder: 'Enter your password...',
            signInLeavePassword: 'Forgot your password?',
            signInLogiBtn: 'Log in',
            signInReturnToTitle: 'Return to',
            signInMainPage: 'Main page',
        },
        layoutUser: {
            layoutCompanyName: 'Site Name',
            layoutLinkAnalytics: 'Analytics',
            layoutLinkShop: 'Shop',
            layoutLinkCategories: 'Categories',
            layoutLinkProducts: 'Product',
            layoutLinkOrders: 'Orders',
            layoutLinkMessage: 'Message',
            layoutLinkSettings: 'Settings',
            layoutLinkExit: 'Exit',
        },
        userShopView: {
            userShopTitle: 'Shop',
            userShopInfoName: 'Shop name:',
            userShopInfoTel: 'Contact phone number:',
            userShopInfoTel2: 'Additional contact phone number:',
            userShopInfoAddress: 'Address:',
            userShopInfoCurrency: 'Currency:',
            userShopInfoLanguage: 'Site language:',
            userShopInfoDelivery: 'Delivery methods:',
            userShopInfoPayment: 'Payment methods:',
            userShopInfoDescription: 'Description of the store:',
            userShopInfoLogo: 'Logo:',
            userShopEditBtn: 'Edit',
            userShopBlockMainTitle: 'Add a block of information',
            userShopBlockTitle: 'Enter a title',
            userShopBlockText: 'Enter the text',
            userShopBlockHeaderColor: 'Header color',
            userShopBlockTextColor: 'Text color',
            userShopBlockBackgroundColor: 'Background color',
            userShopBlockTextAlign: 'Text alignment',
            userShopBlockTitleShadow: 'Title shadow',
            userShopBlockTextShadow: 'Text shadow',
            userShopBlockHeaderSize: 'Header size',
            userShopBlockHeaderThickness: 'Header thickness',
            userShopBlockTextSize: 'Text size',
            userShopBlockTextThickness: 'Text thickness',
            userShopBlockShadowX: 'Shadow by X',
            userShopBlockShadowY: 'Shadow by Y',
            userShopBlockShadowZ: 'Shadow by Z',
            userShopBlockShadowTransparency: 'Shadow transparency',
            userShopBlockRemoveBtn: 'Remove',
            userShopBlockCreateBtn: 'Create',
            userShopBlockInstruction: 'Fill in the block with information and click create. The block will appear on the main page of the store.',
            userShopBlockViewTitle: 'Block view',
            userShopBlockCheckboxStart: 'Start',
            userShopBlockCheckboxCenter: 'Center',
            userShopBlockCheckboxEnd: 'End',
        },  
        userCategoriesView: {
            userCategoriesModalDelCatTitle: 'Are you sure?',
            userCategoriesModalDelCatText: 'All subcategories of this category will be deleted',
            userCategoriesModalDelCatLeftBtn: 'No',
            userCategoriesModalDelCatRightBtn: 'Yes',
            userCategoriesModalDelSubCatTitle: 'Are you sure?',
            userCategoriesModalDelSubCatText: 'Delete this category',
            userCategoriesModalDelSubCatLeftBtn: 'No',
            userCategoriesModalDelSubCatRightBtn: 'Yes',
            userCategoriesModalEditSubCatTitle: 'Edit category?',
            userCategoriesModalEditSubCatText: 'Enter a new name',
            userCategoriesModalEditCatLeftBtn: 'Cancel',
            userCategoriesModalEditCatRightBtn: 'Confirm',
            userCategoriesTitle: 'My categories',
            userCategoriesErrorCreateLimit: 'You have reached the category limit',
            userCategoriesErrorCreate: 'First you need to create a store',
            userCategoriesCreateLabelName: 'Category name',
            userCategoriesCreateNamePlaceholder: 'Enter a name...',
            userCategoriesCreateLabelImg: 'Picture',
            userCategoriesCreateCatBtn: 'Create a category',
            userCategoriesCreateCatInfo: 'To create a category, enter its name and click the create button. The number of categories is limited to "5". For the correct display of pictures, the picture format should be 16:9. To create a category, you must first create a store. After creating a category, you can create subcategories.',
            userCategoriesCardTitle: 'Category name:',
            userCategoriesCreateSub: 'Create a subcategory',
            userCategoriesSubTitle: 'Subcategories:',
        },
        inputText: {
            inputTextPlaceholder: 'Enter...'
        },
        inputTextarea: {
            inputTextareaPlaceholder: 'Enter...'
        },
        creationShop: {
            creationShopTitle1: 'Creating a store',
            creationShopTitle2: 'Store update',
            creationShopInputNameLabel: 'Name of the store',
            creationShopInputNamePlaceholder: 'Enter a store name...',
            creationShopNameInfo: 'Enter a store name...',
            creationShopInputFacebookPlaceholder: 'Enter facebook url...',
            creationShopFacebookInfo: 'Enter the url address of the facebook page so that your customers can contact and follow your publications.',
            creationShopInputInstagramPlaceholder: 'Enter instagram url...',
            creationShopInstagramInfo: 'Enter the url address of the Instagram page so that your customers can contact and follow your posts.',
            creationShopInputTelLabel: 'Phone number for contact',
            creationShopInputTelPlaceholder: 'Phone...',
            creationShopTelInfo: 'Enter the phone number by which customers can contact you. In the format XXX-XXX-XXXX',
            creationShopInputTel2Label: 'Additional phone for communication',
            creationShopInputTel2Placeholder: 'Phone...',
            creationShopTel2Info: 'Enter an additional phone number where customers can contact you. In the format XXX-XXX-XXXX',
            creationShopInputAddressLabel: 'Store address',
            creationShopInputAddressPlaceholder: 'Address...',
            creationShopAddressInfo: 'Enter the address of your store',
            creationShopInputDeliveryLabel: 'Delivery',
            creationShopInputDeliveryPlaceholder: 'Delivery...',
            creationShopDeliveryInfo: 'Enter the methods of delivery of goods in your store',
            creationShopInputPaymentLabel: 'Payment',
            creationShopInputPaymentPlaceholder: 'Payment...',
            creationShopPaymentInfo: 'Enter the payment methods for the goods in your store',
            creationShopInputDescriptionLabel: 'Description',
            creationShopInputDescriptionPlaceholder: 'Enter a description...',
            creationShopDescriptionInfo: 'Enter a few words about your store.',
            creationShopInputCurrencyLabel: 'Currency',
            creationShopCurrencyInfo: 'Enter the currency in which product prices will be indicated, in the format $ € ₴ ...',
            creationShopInputLanguageLabel: 'Language',
            creationShopLanguageInfo: 'Choose the language in which your store will be',
            creationShopInputLogoLabel: 'Logo',
            creationShopLogoInfo: 'Choose your store logo',
            creationShopCancelBtn: 'Cancel',
            creationShopUpdateBtn: 'Update',
            creationShopCreateBtn: 'Create',
        },
        userProduct: {
            userProductTitle: 'My products',
            userProductModalDelTitle: 'Are you sure?',
            userProductModalDelText: 'Remove this product',
            userProductModalDelLeftBtn: 'No',
            userProductModalDelRightBtn: 'Yes',
            userProductSubTitle: 'The total number of:',
            userProductCreateBtn: 'Create a product',
            userProductSearchLabel: 'Product search',
            userProductSearchPlaceholder: 'Enter a name...',
            userProductSortLabel: 'Sort:',
            userProductSortOptionAll: 'All product',
            userProductCardName: 'Product name:',
            userProductCardCategory: 'Category:',
            userProductCardPrice: 'Product price:',
            userProductCardNewPrice: 'Price with discount:',
            userProductCardColors: 'Available colors:',
            userProductCardSizes: 'Available sizes:',
            userProductCardDescription: 'Description:',
            userProductProductMissing: 'The product is missing',
        },
        creationProduct: {
            creationProductNameLabel: 'Product name',
            creationProductNameInfo: 'Enter the name of the product. A product without a name, category and price will not be displayed in your store.',
            creationProductCategoryTitle: 'Category:',
            creationProductCategoryLabel: 'Select a product category',
            creationProductCategoryPlaceholder: 'Search...',
            creationProductCategoryInfo: 'Select a product category.',
            creationProductPriceLabel: 'Price',
            creationProductPriceInfo: 'Enter the price of the product',
            creationProductNewPriceLabel: 'The price of the product, if there is a discount',
            creationProductNewPriceInfo: 'If the product has a discount, enter the price including the discount',
            creationProductDescriptionLabel: 'Product description',
            creationProductDescriptionPlaceholder: 'Description...',
            creationProductDescriptionInfo: 'Enter the product description',
            creationProductColorsLabel: 'Available colors',
            creationProductColorsInfo: 'Enter the color names of your product',
            creationProductSizesLabel: 'Available sizes',
            creationProductSizesInfo: 'Enter the available sizes of your product',
            creationProductPicturesLabel: 'Pictures',
            creationProductPicturesInfo: 'Upload product images.',
            creationProductWarningText: 'These fields are mandatory',
            creationProductCancelBtn: 'Cancel',
            creationProductUpdateBtn: 'Update',
            creationProductCreateBtn: 'Create',
        },
        userPurchases: {
            userPurchasesTitle: 'My orders',
            userPurchasesSortTitle: 'Status:',
            userPurchasesSortOption1: 'All',
            userPurchasesSortOption2: 'In process',
            userPurchasesSortOption3: 'Done',
            userPurchasesSortOption4: 'Rejected',
            userPurchasesFilterTitle: 'Select all:',
            userPurchasesStatusTitle: 'Status',
            userPurchasesErrorText: 'The message list is empty',
        },
        selectStatus: {
            selectStatusOption1: 'In process',
            selectStatusOption2: 'Done',
            selectStatusOption3: 'Rejected',
        },
        readPurchasesView: {
            readPurchasesModDelTitle: 'Are you sure?',
            readPurchasesModDelText1: 'Restore this product',
            readPurchasesModDelText2: 'Remove this product',
            readPurchasesModEditTitle: 'Edit',
            readPurchasesModEditText: 'Enter a new value',
            readPurchasesModEditLeftBtn: 'Cancel',
            readPurchasesModEditRightBtn: 'Confirm',
            readPurchasesOrderTitle: 'Order:',
            readPurchasesStatusTitle: 'Status:',
            readPurchasesStatusOption1: 'In process',
            readPurchasesStatusOption2: 'Done:',
            readPurchasesStatusOption3: 'Rejected:',
            readPurchasesInfoNameTitle: 'Customer:',
            readPurchasesInfoTelTitle: 'Phone:',
            readPurchasesInfoEmailTitle: 'Email:',
            readPurchasesInfoAddressTitle: 'Address:',
            readPurchasesInfoDeliveryTitle: 'Delivery method:',
            readPurchasesInfoPaymentTitle: 'Payment method:',
            readPurchasesInfoCommentTitle: 'Comment:',
            readPurchasesTextareaLabel: 'Make notes',
            readPurchasesTextareaPlaceholder: 'Notes...',
            readPurchasesListNotesTitle: 'Importantly!!!',
            readPurchasesProductsListTitle: 'Ordered product',
            readPurchasesProductsCountTitle: 'Quantity of goods:',
            readPurchasesProductsTotalTitle: 'Order amount:',
            readPurchasesCardNameTitle: 'Product name:',
            readPurchasesCardCategoryTitle: 'Category:',
            readPurchasesCardPriceTitle: 'Product price:',
            readPurchasesCardPrice2Title: 'Price with discount:',
            readPurchasesCardColorsTitle: 'Ordered colors:',
            readPurchasesCardSizeTitle: 'Ordered sizes:',
            readPurchasesCardDescriptionTitle: 'Description:',
            readPurchasesCardCountTitle: 'Quantity:',
            readPurchasesCardSumTitle: 'Sum:',
        },
    },
  
}

